spring:
  datasource:
    username: postgres
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '20000'
    url: jdbc:postgresql://localhost:5432/companies
    password: postgres
  application:
    name: companies-crud

server:
  servlet:
    context-path: /companies-crud
  port: '8081'

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE