server:
  port: 7777

spring:
  application:
    name: config-server
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2piradrian/companies-microservices.git
          search-paths: microservices-config
          default-label: main
          clone-on-start: true

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.config: DEBUG
